package com.zivilon.cindercore.mixins;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Dynamic;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.Mutable;
import org.spongepowered.asm.mixin.gen.Accessor;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityList;
import net.minecraft.entity.DataWatcher;
import java.util.List;
import java.util.Map;

@Mixin(EntityList.class)
public interface MixinEntityList {
    @Accessor("classToIDMapping")
    Map<Class<? extends Entity>, Integer> get_class_to_id_mapping();
}
